v = input('Digite algo: ')
print('O tipo primitivo dessa váriavel é: ', type(v))
print('Só tem espaços?',v.isspace())
print('É composto somente de letra?', v.isalpha())
print('É composto somente por números?', v.isnumeric())
print('É composto por letras ou números?', v.isalnum())
print('Está em maiúsculas?', v.isupper())
print('Está em minúsculas?', v.islower())
print('Está em maiúsculas e minúsculas?', v.istitle())