nc = str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome...')
print('EM MAIÚSCULAS: {}'.format(nc.upper()))
print('EM MINÚSCULAS: {}'.format(nc.lower()))
# print('O nome completo tem {} letras'.format(len(nc.replace(' ', ''))))
print('O nome completo tem {} letras'.format(len(nc)-nc.count(' ')))
#nc = nc.split()
#print('O primeiro nome tem {} letras'.format(len(nc[0])))
print('O primeiro nome tem {} letras'.format(nc.find(' ')))